use_frameworks!

platform :ios, '8.0'

target 'HYHScrollOffsetManager_Example' do
  pod 'HYHScrollOffsetManager', :path => '../'

  target 'HYHScrollOffsetManager_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
